"""Validation on Oct-Nov 2025: how often the checks raise a monitor on ordinary days, and how big a drop they catch.

    python src/validate.py HOURLY.json [--out docs]

HOURLY is a backfill covering 3 Sep - 30 Nov 2025 (28 days of history before 1 Oct):
    python src/backfill.py .cache/hourly_2025.json --end 2025-11-30 --days 89 --cache .cache/archive

Writes docs/VALIDATION.md and docs/validation_daily.csv. Every number in them comes from this script, with the
thresholds exactly as they are in scorer.py at the commit named in the report.
"""
import argparse, copy, csv, datetime as dt, json, os, subprocess, time

import backfill, scorer

FIRST, LAST = dt.date(2025, 10, 1), dt.date(2025, 11, 30)
SCORE_HOUR = 17  # each day is scored at 17:00 IST, when the 11:00-17:00 window is complete
PLANT_AT = dt.datetime(2025, 11, 30, 23)
DROPS = (0.2, 0.3, 0.4, 0.6)
STATUSES = ("ok", "watch", "flag", "nodata")


def day_label(d):
    return f"{d.day} {d:%b %Y}"


def plant(hourly, sid, drop, now):
    """One station's PM10 cut by `drop` from 11:00 to 16:59 IST on each of the 7 days before `now`."""
    out = copy.deepcopy(hourly)
    pm10 = out[str(sid)]["pm10"]
    for k in pm10:
        t = dt.datetime.strptime(k, "%Y-%m-%dT%H")
        if 11 <= t.hour <= 16 and (now - t).days < 7:
            pm10[k] *= 1 - drop
    return out


def daily_run(hourly, stations):
    """Per-day counts, and per monitor the number of days it was flagged."""
    rows, prev, flag_days = [], None, {}
    names = {s["id"]: s["name"] for s in stations}
    for n in range((LAST - FIRST).days + 1):
        day = FIRST + dt.timedelta(days=n)
        latest, _ = scorer.score(hourly, stations, dt.datetime(day.year, day.month, day.day, SCORE_HOUR))
        status = {s["id"]: s["status"] for s in latest["stations"]}
        row = {"date": day.isoformat(), **{st: sum(v == st for v in status.values()) for st in STATUSES}}
        # a change between two answers; going to or from 'no data' is the feed, not the checks
        row["changed"] = None if prev is None else sum(
            prev[i] != status[i] for i in status if "nodata" not in (prev[i], status[i]))
        rows.append(row)
        prev = status
        for i, v in status.items():
            if v == "flag":
                flag_days[names[i]] = flag_days.get(names[i], 0) + 1
    return rows, flag_days


def planted_run(hourly, stations):
    base = {s["id"]: s for s in scorer.score(hourly, stations, PLANT_AT)[0]["stations"]}
    quiet = [i for i, s in base.items() if all(c["status"] == "ok" for c in s["checks"].values())]
    out = []
    for drop in DROPS:
        caught = raised = knock = 0
        for q in quiet:
            planted = scorer.score(plant(hourly, q, drop, PLANT_AT), stations, PLANT_AT)[0]["stations"]
            after = {s["id"]: s for s in planted}
            caught += after[q]["status"] == "flag"
            raised += after[q]["status"] in ("watch", "flag")
            knock += sum(after[i]["status"] == "flag" and base[i]["status"] != "flag" for i in base if i != q)
        out.append({"drop": drop, "quiet": len(quiet), "flag": caught, "watch_or_flag": raised, "knock_on_flags": knock})
    return out


def report(days, flag_days, planted, commit, n_stations):
    judged = [d for d in days if d["ok"] + d["watch"] + d["flag"]]

    def share(st):
        return 100 * sum(d[st] / (d["ok"] + d["watch"] + d["flag"]) for d in judged) / len(judged)

    def span(st):
        return f"{min(d[st] for d in days)}-{max(d[st] for d in days)} monitors"

    changes = [d["changed"] for d in days if d["changed"] is not None]
    top = sorted(flag_days.items(), key=lambda kv: -kv[1])
    top3, total = top[:3], sum(flag_days.values())
    full = next((p["drop"] for p in planted if p["flag"] == p["quiet"]), None)
    lines = [
        "# Validation: Oct-Nov 2025",
        "",
        f"_Generated by `src/validate.py` with the thresholds in `src/scorer.py` at commit `{commit}`. Do not edit by hand._",
        "",
        f"Every day from {FIRST.day} {FIRST:%b} to {day_label(LAST)}, the {n_stations} monitors were scored at "
        f"{SCORE_HOUR}:00 IST from the public OpenAQ archive, exactly as the live site would have scored them. "
        "Thresholds: physics watch above 1% and flag above 5% of hours; neighbours and history watch at 2 and flag at 3 "
        "robust SDs.",
        "",
        "## On ordinary days",
        "",
        "| | Average per day | Range |",
        "|---|---|---|",
        f"| Doesn't add up (flag) | {share('flag'):.1f}% of judged monitors | {span('flag')} |",
        f"| Worth a look (watch) | {share('watch'):.1f}% | {span('watch')} |",
        f"| Agrees with neighbours (ok) | {share('ok'):.1f}% | {span('ok')} |",
        f"| Not enough data | | {span('nodata')} |",
        f"| Answers that changed from the day before | {sum(changes) / len(changes):.1f} monitors | {min(changes)}-{max(changes)} |",
        "",
        "## Who gets flagged",
        "",
        f"{len(top)} monitors were flagged on at least one day. The three flagged most often account for "
        f"{100 * sum(n for _, n in top3) / total:.0f}% of all flag-days:",
        "",
        *[f"- {name}: {n} of {len(days)} days" for name, n in top3],
        "",
        "## Catching a planted drop",
        "",
        f"For each monitor that passed every check on {day_label(PLANT_AT)}, its daytime (11:00-17:00) PM10 was cut for "
        "the last 7 days, and the whole city was scored again.",
        "",
        "| Daytime PM10 cut | Flagged | Flagged or worth a look | Other monitors newly flagged (all runs) |",
        "|---|---|---|---|",
        *[f"| {p['drop']:.0%} | {p['flag']} of {p['quiet']} | {p['watch_or_flag']} of {p['quiet']} | {p['knock_on_flags']} |"
          for p in planted],
        "",
        "## In plain words",
        "",
        f"On an ordinary day, about {share('flag'):.0f} in 100 judged monitors get \"doesn't add up\" and "
        f"{share('watch'):.0f} in 100 get \"worth a look\". "
        + (f"A monitor whose daytime PM10 is cut by {full:.0%} or more for a week is flagged every time. " if full else "")
        + "Smaller cuts are caught less often; the table above says how often.",
        "",
        "Per-day counts: [`validation_daily.csv`](validation_daily.csv).",
        "",
    ]
    return "\n".join(lines)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("hourly")
    ap.add_argument("--out", default="docs")
    a = ap.parse_args()
    hourly, stations = json.load(open(a.hourly)), backfill.stations()
    commit = subprocess.run(["git", "rev-parse", "--short", "HEAD"], capture_output=True, text=True).stdout.strip() or "unknown"
    t0 = time.time()
    days, flag_days = daily_run(hourly, stations)
    print(f"scored {len(days)} days in {time.time() - t0:.0f} s", flush=True)
    planted = planted_run(hourly, stations)
    print(f"planted runs done in {time.time() - t0:.0f} s: {planted}", flush=True)
    with open(os.path.join(a.out, "validation_daily.csv"), "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=["date", *STATUSES, "changed"])
        w.writeheader()
        w.writerows(days)
    with open(os.path.join(a.out, "VALIDATION.md"), "w", encoding="utf-8") as f:
        f.write(report(days, flag_days, planted, commit, len(stations)))
    print(f"wrote {a.out}/VALIDATION.md")


if __name__ == "__main__":
    main()
